version: '2'
services:
  db:
    image: mysql:latest
    platform: linux/amd64
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: familytree
      MYSQL_USER: person
      MYSQL_PASSWORD: password
  admin:
    image: adminer
    ports:
      - "8080:8080"
